### ISSUE TITLE
[Question] Raspberry 2 is supported?

### ISSUE THREAD

**Issue by darthpelo** [IBM-Swift/Aphid#16]
Hi guys, your project is cool and I want to give a try.
I have only one question: can I compile on a R Pi2?

Thanks!

**Comment by rfdickerson** [comment]
Cool! We only tried on a Pi3 and Beaglebone. Give R Pi2 a shot, should work I think. Let us know!

**Comment by rfdickerson** [comment]
@darthpelo , can you let us know if the Pi2 worked for you? :)

**Comment by darthpelo** [comment]
@rfdickerson I am sorry for the lack of news, but I was stucked on Swift 3.0 migration on some work projects :(
I tried yesterday with this Swift version:
Swift version 3.0-dev (LLVM a4d7129463, Clang 968470f170, Swift 1730bffee6)
but I have some errors&warnings building the libdispatch library (step 4 https://github.com/IBM-Swift/Aphid/wiki/Compiling-an-Aphid-Application-on-the-Pi-3#compile-dispatch-that-works-on-arm).

**Comment by rfdickerson** [comment]
@darthpelo you should check out this really good tutorial on building on the Pi:
http://dev.iachieved.it/iachievedit/building-swift-3-0-on-an-armv7-system/

I think it will build dispatch now fine without needing special steps? Could be wrong. @jmarcelino ?

**Comment by darthpelo** [comment]
Yep, I used http://dev.iachieved.it posts to setup my Pi2 (I am using swift 3.0). I will do other tests.
Thanks!
