### ISSUE TITLE
Running only on localhost

### ISSUE THREAD

**Issue by hengel2810** [IBM-Swift/Aphid#22]
I implemented the following Client-Class:

`import Aphid
import Foundation

class Client: Aphid, MQTTDelegate {
    
    init(clientId: String, host:String, port:Int32) {
        super.init(clientId: clientId, cleanSess: true, username: nil, password: nil, host: host, port: port)
        super.delegate = self
    }
    
    func didConnect() {
        print("I connected!")
    }
    func didLoseConnection() {
        print("connection lost")
    }
    public func didLoseConnection(error: Error?) {
        print("connection lost ERROR: \(error)")
    }
    
    func didCompleteDelivery(token: String) {
        print("didCompleteDelivery \(token)")
    }
    
    func didReceiveMessage(topic: String, message: String) {
        print("didReceiveMessage \(topic) \(message)")
    }
}`

In the main.swift I run following code:
`import Foundation
import Aphid

print("START")
let client = Client(clientId: "abc12345", host: "hengel28.net", port: 1883)
try client.connect()
client.subscribe(topic: ["dht11"], qoss: [QosType.atMostOnce])
client.subscribe(topic: ["dht11"], qoss: [QosType.atLeastOnce])
client.subscribe(topic: ["dht11"], qoss: [QosType.exactlyOnce])
client.publish(topic: "test11", withMessage: "swift test")

CFRunLoopRun()`

So, I've created an Docker container from the ncarlier/mqtt image which uses mosquito as broker. Running the container locally on my mac and connect over localhost, it's working. If I connect to my DigitalOcean Droplet with the same Docker container, it is not working. With some testing apps like MQTT.fx it is also working with the DO-hosted container.

Tested everything, but I can't get it running. Hope somebody can help.

**Comment by kweinmeister** [comment]
@hengel2810 Can you confirm that this has been fixed by PR #25 in the latest release?

**Comment by kweinmeister** [comment]
Closing, as this is assumed to have been resolved by PR #25.
