### ISSUE TITLE
Activating QoS >= 1 Appears to Mutate Messages

### ISSUE THREAD

**Issue by chrimifi** [IBM-Swift/Aphid#26]
I have two Swift programs using Aphid to communicate over MQTT and have noticed that the message (as passed in to the MQTTDelegate `didReceiveMessage` function we define) will change if QoS is set to 1 or 2. For instance, when one of the clients is set to QoS 0, the message is reported by the Xcode debugger as `"{\"type\":\"hello\"}"`. When both are set to QoS >=1, the message is reported by the Xcode debugger as `"\0\u{1}{\"type\":\"hello\"}"`.

Shortly after this, the program will crash at Publish.swift#43, saying that an optional was unexpectedly unwrapped to `nil`. I'm not 100% sure if this is related (and please forgive me if I'm out of my depth), but it seems like it could be to me because that line masks a number with 0x08, which will make the output either 0 or 8, which it then passes to the QosType constructor, which expects 0, 1, or 2.

The broker I'm using is Mosquitto, no encryption is turned on, and this is all happening on the same machine. One of the Swift programs is command-line and the other is an iOS app, but this happens in in both directions.

**Comment by kweinmeister** [comment]
@chrimifi Do you have a simple test project that can reproduce the issue?

**Comment by chrimifi** [comment]
Everything is wrapped up in work code... but I tinkered with how the QoS bit is read and things seem to be fixed. I'll try to put a couple of tests in place and submit a PR.

**Comment by kweinmeister** [comment]
Fixed in PR #29
