### ISSUE TITLE
Why is there no example for a simple iOS App?

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM-Swift/Aphid#27]
Why is there no example for a simple iOS App?

It should contain following steps or content:

a) Maybe using the https://quickstart.internetofthings.ibmcloud.com/iotsensor/ as device type
b) Setup SSL to IBM IoT connection
c) Connect to device
d) GetMessage from IoT device
e) SendMessage to IoT device 

Optional: If needed help to understand how to handle possible cors challenges.

**Comment by kweinmeister** [comment]
There is a [repo](https://github.com/IBM-Swift/AphidClient) with examples of how to use Aphid from a client. PRs or sample projects with more examples are welcome.
